# Generated by Django 4.2.3 on 2023-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('area', models.DateField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('parking', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('path', models.DateField()),
            ],
        ),
    ]
